version: "3"
 
services:
  uwsgi:
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=dockerized_project.settings.production
    volumes:
      - ./docker_volumes/static:/code/dockerized_project/static
 
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
 
  app:
    image: nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
 
  static:
    image: nginx
    volumes:
      - ./nginx/static.conf:/etc/nginx/nginx.conf
      - ./docker_volumes/static:/static